"""
State-Specific Assessment & Contract Rules

50-state knowledge base for home care assessment requirements,
billing codes, recording consent, and licensing rules.

The AI pipeline calls get_state_rules(state_code) to inject only
the relevant state's requirements into the LLM prompt.
"""

# ─── Recording Consent ───────────────────────────────────────────────────────

TWO_PARTY_CONSENT_STATES = {
    "CA", "CT", "DE", "FL", "IL", "MD", "MA", "MI", "MT", "NH", "PA", "WA",
}
# Oregon is two-party for in-person only, one-party for phone
OREGON_MIXED_CONSENT = True

# ─── Per-State Rules ─────────────────────────────────────────────────────────
# Each entry contains only what the AI needs to generate a correct contract
# and run a compliant assessment for that state.

STATE_RULES = {
    "AL": {
        "name": "Alabama",
        "medicaid_program": "Alabama Medicaid",
        "hcbs_waivers": "Elderly & Disabled (E&D) Waiver, SAIL Waiver, Living at Home Waiver",
        "assessment_tool": "State-developed Comprehensive Assessment Tool",
        "assessment_requirements": "Comprehensive needs assessment by RN or social worker; includes medical, functional, cognitive, and social evaluation.",
        "reassessment_frequency": "Annual; more frequently if condition changes",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by Alabama Department of Public Health. Personal care agencies also require licensure.",
        "billing_codes": "T1019 (PCS per 15 min), S5125 (attendant care), S5130 (homemaker)",
        "key_regulations": "Alabama Admin Code Chapter 420-5-18 (Home Health Agencies)",
        "special_requirements": "Criminal background checks required; TB screening; 40-hour initial aide training",
    },
    "AK": {
        "name": "Alaska",
        "medicaid_program": "Alaska Medicaid",
        "hcbs_waivers": "Adults with Physical Disabilities (APD), Community First Choice (1915(k))",
        "assessment_tool": "State Consumer Assessment Tool",
        "assessment_requirements": "Functional assessment determining level of care and service authorization.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home and community-based services agencies licensed by DHSS.",
        "billing_codes": "T1019 (PCS), S5125 (attendant care)",
        "key_regulations": "7 AAC 43 (Home and Community-Based Services)",
        "special_requirements": "Self-directed personal care option available; background check registry",
    },
    "AZ": {
        "name": "Arizona",
        "medicaid_program": "AHCCCS (Arizona Health Care Cost Containment System)",
        "hcbs_waivers": "Arizona Long-Term Care System (ALTCS)",
        "assessment_tool": "Pre-Admission Screening (PAS) by ALTCS case manager",
        "assessment_requirements": "Comprehensive functional assessment including ADLs, IADLs, cognitive/behavioral status, medical needs, caregiver availability, risk assessment.",
        "reassessment_frequency": "Annual; quarterly monitoring contacts",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by ADHS. Non-medical attendant care agencies need AHCCCS provider registration.",
        "billing_codes": "T1019 (attendant care), T1020 (per diem), S5130 (homemaker)",
        "key_regulations": "A.R.S. § 36-151 et seq.; AHCCCS Medical Policy Manual, Chapter 1200",
        "special_requirements": "AHCCCS is a managed care model; services authorized through MCOs. Fingerprint clearance card required.",
    },
    "AR": {
        "name": "Arkansas",
        "medicaid_program": "Arkansas Medicaid",
        "hcbs_waivers": "ARChoices in Homecare, ElderChoices",
        "assessment_tool": "Arkansas Assessment Instrument (independent assessor)",
        "assessment_requirements": "Independent Assessment by state-contracted assessor; RN assessment for skilled care. ADLs scored 0-4.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by Arkansas Dept. of Health. Personal care agencies require DHS certification.",
        "billing_codes": "T1019 (PCS), S5125 (attendant care), S5130 (homemaker)",
        "key_regulations": "Arkansas Medicaid Provider Manual, Section 213; DHS Policy 1076",
        "special_requirements": "ARChoices uses independent assessment (not provider-performed); consumer direction option available",
    },
    "CA": {
        "name": "California",
        "medicaid_program": "Medi-Cal",
        "hcbs_waivers": "In-Home Supportive Services (IHSS), HCBS Waiver, Assisted Living Waiver, MSSP",
        "assessment_tool": "Uniform Assessment Tool (county social workers for IHSS); OASIS for Medicare HHA",
        "assessment_requirements": "ADLs, IADLs, cognition, mental health, medical needs, paramedical services, protective supervision.",
        "reassessment_frequency": "Annual IHSS reassessment; more frequently as needed",
        "recording_consent": "two-party (Cal. Penal Code § 632)",
        "licensing": "Home health agencies licensed by CDPH. Home Care Organization (HCO) registration for non-medical home care.",
        "billing_codes": "T1019 (PCS), S5125, IHSS uses functional index ranking",
        "key_regulations": "Welf. & Inst. Code § 12300 et seq. (IHSS); HSC § 1796.10 et seq. (Home Care Services)",
        "special_requirements": "Home Care Services Consumer Protection Act requires HCO registration, caregiver background checks, and DOJ/FBI fingerprinting. TWO-PARTY CONSENT FOR ALL RECORDINGS.",
    },
    "CO": {
        "name": "Colorado",
        "medicaid_program": "Health First Colorado",
        "hcbs_waivers": "EBD (Elderly, Blind, Disabled), SLS, CHRP, CES, BI",
        "assessment_tool": "Uniform Long-Term Care (ULTC) 100.2 assessment",
        "assessment_requirements": "Determines functional eligibility and service needs. ADLs, IADLs, cognition, behavior, medical conditions, risk factors.",
        "reassessment_frequency": "Annual; review at significant change",
        "recording_consent": "one-party",
        "licensing": "Class A for skilled, Class B for non-medical. Personal care agencies require HCPF enrollment.",
        "billing_codes": "T1019 (PCS), S5125 (attendant care), S5130 (homemaker)",
        "key_regulations": "6 CCR 1011-1 Chapter 26 (Home Care Agencies); 10 CCR 2505-10 (HCBS waivers)",
        "special_requirements": "Consumer-directed attendant support (CDAS) option; DORA background checks required",
    },
    "CT": {
        "name": "Connecticut",
        "medicaid_program": "HUSKY Health",
        "hcbs_waivers": "CT Home Care Program for Elders, PCA Waiver, ABI/MFP Waiver",
        "assessment_tool": "CT Uniform Assessment (UA) tool",
        "assessment_requirements": "Comprehensive assessment completed by care manager. ADLs, IADLs, cognition, behavioral health, medical needs, informal supports, environmental safety, risk.",
        "reassessment_frequency": "Annual; quarterly care plan review",
        "recording_consent": "two-party (Conn. Gen. Stat. § 52-570d)",
        "licensing": "Home health care agencies and homemaker-companion agencies licensed by DPH.",
        "billing_codes": "T1019 (PCS), S5125, S5135 (companion)",
        "key_regulations": "CGS § 19a-490 et seq.; RCSA § 19-13-D66 through D77",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. PCA program allows self-direction.",
    },
    "DE": {
        "name": "Delaware",
        "medicaid_program": "Diamond State Health Plan",
        "hcbs_waivers": "DDDS Waiver, DSAMH Waiver, DSHP Plus (managed LTSS)",
        "assessment_tool": "Delaware Comprehensive Assessment Tool (MCO care coordinator)",
        "assessment_requirements": "ADLs, IADLs, cognitive/behavioral, medical, social supports, environmental, risk factors.",
        "reassessment_frequency": "Annual",
        "recording_consent": "two-party (Del. Code tit. 11, § 2402)",
        "licensing": "Home health agencies licensed by Office of Health Facilities Licensing. Personal attendance services regulated under DSHP Plus.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "16 Del. C. Chapter 10 (Facilities Licensing)",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. Managed LTSS through MCOs.",
    },
    "FL": {
        "name": "Florida",
        "medicaid_program": "SMMC (Statewide Medicaid Managed Care)",
        "hcbs_waivers": "Long-Term Care (LTC) Managed Care (SMMC-LTC)",
        "assessment_tool": "CARES (Comprehensive Assessment Review and Evaluation)",
        "assessment_requirements": "CARES for nursing facility level of care; MCO comprehensive assessment. ADLs, IADLs, cognitive status, behavioral health, medical conditions, nutrition, living environment, support systems.",
        "reassessment_frequency": "Annual CARES; MCO quarterly contact",
        "recording_consent": "two-party (Fla. Stat. § 934.03)",
        "licensing": "Home health agencies licensed by AHCA. Nurse registries for personal care.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135 (companion)",
        "key_regulations": "Fla. Stat. Ch. 400 Part III (Home Health); Ch. 409 (Medicaid); 59A-8 FAC",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. All HCBS through managed care. CARES determination required for LTSS.",
    },
    "GA": {
        "name": "Georgia",
        "medicaid_program": "Georgia Medicaid",
        "hcbs_waivers": "Elderly & Disabled Waiver, NOW/COMP (IDD), SOURCE, GAPP",
        "assessment_tool": "Georgia Uniform Assessment Tool",
        "assessment_requirements": "Uniform Assessment by DHS/DFCS. ADLs, IADLs, cognitive function, behavioral needs, medical, support systems, environmental safety.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Private home care providers licensed by DCH. Home health agencies licensed by DHR.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "O.C.G.A. § 31-7 (Health Care Facilities); Georgia Medicaid Provider Manual",
        "special_requirements": "Employee Dishonesty Bond required; administrator must have qualifying experience",
    },
    "HI": {
        "name": "Hawaii",
        "medicaid_program": "Med-QUEST",
        "hcbs_waivers": "Community Care Foster Family Home, 1915(c) waiver",
        "assessment_tool": "Modified interRAI and state-developed tools",
        "assessment_requirements": "Comprehensive functional assessment. ADLs, IADLs, cognitive, behavioral, medical, social, environmental.",
        "reassessment_frequency": "Annual; more frequently as clinically indicated",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DOH. Personal care agencies regulated under Med-QUEST provider enrollment.",
        "billing_codes": "T1019 (PCS), S5125",
        "key_regulations": "HRS Chapter 321 (DOH); HAR Title 11, Chapter 97 (Home Health)",
        "special_requirements": "Geographic challenges (island-based services); cultural competency emphasis",
    },
    "ID": {
        "name": "Idaho",
        "medicaid_program": "Idaho Medicaid",
        "hcbs_waivers": "Aged & Disabled Waiver, DD Waiver",
        "assessment_tool": "Uniform Assessment Tool (UAT) by DHW assessors",
        "assessment_requirements": "ADLs scored 1-4, IADLs, cognitive status, behavioral needs, medical conditions, living situation, informal supports.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Personal assistance agencies licensed by DHW. Home health agencies licensed by Bureau of Facility Standards.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "IDAPA 16.03.10 (Medicaid); IDAPA 16.03.07 (Home Health)",
        "special_requirements": "Self-directed community supports option; fiscal intermediary services",
    },
    "IL": {
        "name": "Illinois",
        "medicaid_program": "HealthChoice Illinois (Managed Care)",
        "hcbs_waivers": "Supportive Living, DOA HCBS Waiver, DORS HSP Waiver",
        "assessment_tool": "Comprehensive Care Coordination (CCC) assessment; DOA Determination of Need (DON) screening",
        "assessment_requirements": "ADLs, IADLs, cognitive/behavioral, medical needs, living environment, support systems. DON score 29+ for eligibility.",
        "reassessment_frequency": "Annual DON; care plan review every 6 months",
        "recording_consent": "two-party (720 ILCS 5/14-2)",
        "licensing": "Home health and home services agencies licensed by IDPH under Home Health, Home Services, and Home Nursing Agency Licensing Act.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "210 ILCS 55/ (Home Health Licensing Act); 77 Ill. Admin. Code 245",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. DON score determines service eligibility and hours. Managed care coordination required.",
    },
    "IN": {
        "name": "Indiana",
        "medicaid_program": "Indiana Health Coverage Programs (IHCP)",
        "hcbs_waivers": "Aged & Disabled Waiver, TBI Waiver",
        "assessment_tool": "Indiana Assessment Tool by FSSA Area Agency on Aging",
        "assessment_requirements": "Level of Care (LOC) assessment. ADLs, IADLs, cognitive status, behavioral needs, medical conditions, support systems, environmental safety.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by ISDH. Personal services agencies licensed under IC 16-27.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "IC 16-27 (Home Health); 410 IAC 17 (Licensure); IHCP Provider Manual",
        "special_requirements": "Structured Family Caregiving option; CHOICE program for consumer-directed care",
    },
    "IA": {
        "name": "Iowa",
        "medicaid_program": "IA Health Link (Managed Care)",
        "hcbs_waivers": "Elderly Waiver, Health & Disability Waiver, Brain Injury Waiver, HCBS ID Waiver",
        "assessment_tool": "Iowa Case Management Comprehensive Assessment (Form 470-4694) — 8-section assessment with 63+ risk factors",
        "assessment_requirements": "Consumer Information (demographics, legal), Medical & Physical Health (R1-R32), Mental Health/Behavioral/Substance Use (R33-R44), Housing & Environment (R45-R63), Social, Transportation, Education, Vocational.",
        "reassessment_frequency": "Annual comprehensive; 6-month review",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by IDPH. Homemaker-home health aide agencies under Iowa Code Chapter 135C.",
        "billing_codes": "T1019 (PCS per 15 min), T1020 (PCS per diem), S5125, S5130",
        "key_regulations": "Iowa Code § 249A; Iowa Admin. Code 441, Chapter 78; Chapter 77",
        "special_requirements": "Managed care through MCOs (Amerigroup, Molina). Consumer-directed attendant care (CDAC) option. Form 470-4694 risk factor scoring system.",
    },
    "KS": {
        "name": "Kansas",
        "medicaid_program": "KanCare (Managed Care)",
        "hcbs_waivers": "FE (Frail Elderly), PD (Physical Disability), TBI, TA, IDD, SED",
        "assessment_tool": "CARE (Client Assessment Referral and Evaluation) tool",
        "assessment_requirements": "Functional Eligibility Assessment (FEA). ADLs (scored), IADLs, cognitive function, behavioral needs, medical, support needs, environmental.",
        "reassessment_frequency": "Annual functional reassessment",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by KDHE. HCBS agencies through KDADS enrollment.",
        "billing_codes": "T1019 (PCS), S5125 (attendant care), S5130 (homemaker)",
        "key_regulations": "K.S.A. 65-5101 et seq.; K.A.R. 26-41 (HCBS); KanCare provider manual",
        "special_requirements": "All Medicaid through managed care (KanCare MCOs). Self-directed services available.",
    },
    "KY": {
        "name": "Kentucky",
        "medicaid_program": "Kentucky Medicaid",
        "hcbs_waivers": "HCB, MPW (Michelle P. Waiver), ABI, Model II Waiver",
        "assessment_tool": "MAP-351 assessment tool",
        "assessment_requirements": "Performed by DAIL assessors. ADLs, IADLs, cognitive status, behavioral health, medical needs, living situation, support systems.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by Office of Inspector General. PCAs certified by CHFS.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "KRS Chapter 216; 907 KAR 1:045 (PCS); 907 KAR 3:005 (HCBS)",
        "special_requirements": "Community First Choice (1915(k)) implemented; consumer-direction option",
    },
    "LA": {
        "name": "Louisiana",
        "medicaid_program": "Healthy Louisiana (Managed Care)",
        "hcbs_waivers": "Community Choices Waiver (CCW), ROW, NOW/LTPCS",
        "assessment_tool": "MDS-HC (interRAI) for LTPCS",
        "assessment_requirements": "Comprehensive assessment by Support Coordinator. ADLs, IADLs, cognitive/behavioral, medical, informal supports, environmental, financial, risk.",
        "reassessment_frequency": "Annual; quarterly monitoring",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by LDH. Personal care agencies enrolled as LTPCS providers.",
        "billing_codes": "T1019 (PCS), T1020 (PCS per diem), S5125",
        "key_regulations": "LAC Title 48; La. R.S. 40:2116 et seq.",
        "special_requirements": "LTPCS uses MDS-HC scoring for service authorization. Self-direction through EVV-verified services.",
    },
    "ME": {
        "name": "Maine",
        "medicaid_program": "MaineCare",
        "hcbs_waivers": "Section 19 (Elderly & Adults with Disabilities), Section 29, Section 21",
        "assessment_tool": "Maine Assessment Tool",
        "assessment_requirements": "Comprehensive functional assessment by case manager. ADLs, IADLs, cognitive, behavioral, medical, living environment, informal supports, safety.",
        "reassessment_frequency": "Annual; more frequently as needed",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DHHS. PCAs licensed under new 2024 rule.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "10-144 CMR Ch. 110 (MaineCare); 10-144 CMR Ch. 12 (Home Health)",
        "special_requirements": "New PCA licensing rule effective August 2024. Self-directed personal care option through Section 19.",
    },
    "MD": {
        "name": "Maryland",
        "medicaid_program": "HealthChoice (Managed Care)",
        "hcbs_waivers": "Community Options Waiver, Waiver for Older Adults, Model Waiver, TBI Waiver",
        "assessment_tool": "interRAI Home Care assessment",
        "assessment_requirements": "Long-Term Care Assessment by local DSS. ADLs, IADLs, cognitive/behavioral, medical needs, environmental safety, social supports, risk assessment.",
        "reassessment_frequency": "Annual; semi-annual review for some waivers",
        "recording_consent": "two-party (Md. Code, Cts. & Jud. Proc. § 10-402)",
        "licensing": "Home health agencies licensed by OHCQ. RSAs for personal care licensed separately.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "COMAR 10.07.10 (Home Health); COMAR 10.07.05 (RSA)",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. Community First Choice (1915(k)) implemented. EVV required.",
    },
    "MA": {
        "name": "Massachusetts",
        "medicaid_program": "MassHealth",
        "hcbs_waivers": "Frail Elder Waiver, ABI/MFP Waiver, Community Living Waiver",
        "assessment_tool": "MassHealth Clinical Assessment; Independent living assessment by ASAP",
        "assessment_requirements": "ADLs, IADLs, cognitive function, behavioral health, medical needs, environmental safety, social supports.",
        "reassessment_frequency": "Annual; 90-day review for new enrollees",
        "recording_consent": "two-party (Mass. Gen. Laws ch. 272, § 99) — one of the strictest all-party wiretap laws",
        "licensing": "Home health agencies licensed by DPH. Home care agencies (non-medical) certified by EOEA.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "105 CMR 141.000 (Home Health); 130 CMR 422.000 (PCS)",
        "special_requirements": "TWO-PARTY CONSENT (very strict all-party wiretap law). PCA program with consumer direction. SCO managed care for duals.",
    },
    "MI": {
        "name": "Michigan",
        "medicaid_program": "Healthy Michigan Plan",
        "hcbs_waivers": "MI Choice Waiver, Habilitation Supports Waiver",
        "assessment_tool": "MI Choice screening tool; Level of Care Determination (LOCD)",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, support needs, environmental safety, informal care.",
        "reassessment_frequency": "Annual; 90-day review for MI Choice",
        "recording_consent": "two-party (Mich. Comp. Laws § 750.539c) — for private conversations",
        "licensing": "Home health agencies licensed by LARA. Home help agencies enrolled through MDHHS.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "MCL 333.20101 et seq.; Mich. Admin. Code R 325.20101",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. MI Choice waiver uses supports coordinators.",
    },
    "MN": {
        "name": "Minnesota",
        "medicaid_program": "Medical Assistance (MA) / MinnesotaCare",
        "hcbs_waivers": "Elderly Waiver (EW), CADI, BI, DD, CAC",
        "assessment_tool": "MnCHOICES assessment",
        "assessment_requirements": "Comprehensive long-term care consultation by lead agency assessor. ADLs, IADLs, cognitive, behavioral, medical, environmental, support systems, vocational, financial.",
        "reassessment_frequency": "Annual; review at significant change",
        "recording_consent": "one-party",
        "licensing": "Comprehensive home care license (skilled + basic) or basic home care license from MDH.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "Minn. Stat. § 144A.43-.482 (Home Care); Minn. Stat. § 256B.0651 (PCA)",
        "special_requirements": "PCA Choice option for consumer-directed services. CFSS replacing PCA program. MDH background study required.",
    },
    "MS": {
        "name": "Mississippi",
        "medicaid_program": "MississippiCAN (Managed Care)",
        "hcbs_waivers": "Elderly & Disabled Waiver, IDD Waiver, TBI/SCI Waiver",
        "assessment_tool": "Mississippi Assessment Instrument",
        "assessment_requirements": "Level of Care assessment by Division of Medicaid contractor. ADLs, IADLs, cognitive, behavioral, medical, nursing needs, support systems, environmental.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by MSDH. Personal care agencies through Medicaid enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "Miss. Code § 41-7-191 et seq.; Miss. Admin. Code Title 15 Part 16",
        "special_requirements": "EVV required for PCS. Managed care through MississippiCAN.",
    },
    "MO": {
        "name": "Missouri",
        "medicaid_program": "MO HealthNet",
        "hcbs_waivers": "Aged & Disabled Waiver, Independent Living Waiver, Partnership for Hope",
        "assessment_tool": "Missouri Assessment Tool (by CARO assessment contractor)",
        "assessment_requirements": "Pre-Admission Screening. ADLs scored 0-3 each, IADLs, cognitive status, behavioral needs, medical, environmental, support systems.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DHSS. In-home services agencies licensed under Chapter 197 RSMo.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "RSMo Chapter 197; 19 CSR 30-82 (In-Home Services); 13 CSR 70-91 (HCBS)",
        "special_requirements": "CARO performs independent assessments (not provider-performed). Consumer-directed services option. EVV required.",
    },
    "MT": {
        "name": "Montana",
        "medicaid_program": "Montana Medicaid",
        "hcbs_waivers": "Big Sky Waiver (Elderly/Physically Disabled), HCBS-DD",
        "assessment_tool": "Montana Assessment Tool",
        "assessment_requirements": "Comprehensive Assessment by DPHHS; RN assessment for skilled care. ADLs, IADLs, cognitive, behavioral, medical, living environment, informal supports, safety.",
        "reassessment_frequency": "Annual",
        "recording_consent": "two-party (Mont. Code § 45-8-213)",
        "licensing": "Home health and personal care agencies licensed by DPHHS Quality Assurance Division.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "MCA § 50-5-101 et seq.; ARM 37.40 (Medicaid HCBS)",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. Big Sky Waiver uses self-directed care option.",
    },
    "NE": {
        "name": "Nebraska",
        "medicaid_program": "Heritage Health (Managed Care)",
        "hcbs_waivers": "Aged & Disabled Waiver, DD Waiver, TBI Waiver",
        "assessment_tool": "Nebraska Care Management Program Assessment with SLUMS, PHQ-2/9, NSI, ADL/IADL scoring",
        "assessment_requirements": "Cognitive (SLUMS 30-point exam), Depression (PHQ-2/PHQ-9), Nutrition (NSI 10-question), ADLs (scored per task), IADLs, Housing, Legal, Financial, Social, Medical.",
        "reassessment_frequency": "Annual; 6-month review; significant change reassessment",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DHHS Division of Public Health.",
        "billing_codes": "G0156 (HHA services), S9122 (per hour HHA), T1019 (PCS), S5125",
        "key_regulations": "Neb. Rev. Stat. § 71-401 et seq.; 175 NAC; Nebraska DHHS Medicaid Manual",
        "special_requirements": "Heritage Health managed care. SLUMS, PHQ-2/9, NSI, and ADL/IADL scoring tools.",
    },
    "NV": {
        "name": "Nevada",
        "medicaid_program": "Nevada Medicaid",
        "hcbs_waivers": "HCBS Waiver for Frail Elderly, PCS Waiver",
        "assessment_tool": "Nevada Comprehensive Assessment Tool",
        "assessment_requirements": "Comprehensive Assessment by DHCFP assessors. ADLs, IADLs, cognitive, behavioral, medical, living environment, informal supports, safety.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Personal care agencies licensed by DPBH/HCQC under NRS 449. Home health agencies licensed separately.",
        "billing_codes": "T1019 (PCS), S5125",
        "key_regulations": "NRS 449; NAC 449; NRS 422 (Medicaid)",
        "special_requirements": "Personal care agencies distinctly licensed from employment agencies.",
    },
    "NH": {
        "name": "New Hampshire",
        "medicaid_program": "NH Medicaid Care Management",
        "hcbs_waivers": "CFI (Choices for Independence), DD Waiver, ABD Waiver",
        "assessment_tool": "NH Assessment Tool by Area Agency on Aging or ServiceLink",
        "assessment_requirements": "ADLs, IADLs, cognitive function, behavioral, medical, environmental safety, support systems.",
        "reassessment_frequency": "Annual",
        "recording_consent": "two-party (N.H. Rev. Stat. § 570-A:2)",
        "licensing": "Home health agencies licensed by DHHS. Personal care agencies through Medicaid enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "RSA 151 (Home Health); He-P 809; He-E 801 (CFI)",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. CFI waiver allows consumer-directed services.",
    },
    "NJ": {
        "name": "New Jersey",
        "medicaid_program": "NJ FamilyCare",
        "hcbs_waivers": "MLTSS (Managed Long-Term Services and Supports), GO, TBI, ACCAP",
        "assessment_tool": "NJ CHOICE assessment",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical needs, caregiver resources, environmental, financial, risk.",
        "reassessment_frequency": "Annual through MCO",
        "recording_consent": "one-party",
        "licensing": "CHHA and home care services agencies licensed separately by NJDOH.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "N.J.A.C. 8:42 (Home Health); N.J.S.A. 26:2H; N.J.A.C. 8:42A (Home Care)",
        "special_requirements": "MLTSS through managed care (Amerigroup, Horizon, United). NJ CHOICE is the gateway assessment.",
    },
    "NM": {
        "name": "New Mexico",
        "medicaid_program": "Centennial Care (Managed Care)",
        "hcbs_waivers": "Centennial Care, DD Waiver, Mi Via (self-directed)",
        "assessment_tool": "Comprehensive Needs Assessment (CNA) by MCO care coordinator",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, support systems, cultural considerations.",
        "reassessment_frequency": "Annual by MCO",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DOH. Personal care through MCO provider enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "NMAC 7.28.2 (Home Health); NMSA 1978 § 24-1 (DOH)",
        "special_requirements": "Centennial Care integrates physical health, behavioral health, and LTSS. Culturally competent assessment emphasis.",
    },
    "NY": {
        "name": "New York",
        "medicaid_program": "New York Medicaid",
        "hcbs_waivers": "NHTD, TBI Waiver, OPWDD Waivers",
        "assessment_tool": "UAS-NY (Uniform Assessment System for New York)",
        "assessment_requirements": "Comprehensive standardized assessment. ADLs, IADLs, cognitive patterns, behavioral symptoms, medical complexities, environmental, psychosocial, clinical.",
        "reassessment_frequency": "Annual UAS-NY; semi-annual review for MLTC",
        "recording_consent": "one-party",
        "licensing": "LHCSAs, CHHAs, and LLHCSAs licensed by DOH.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "PHL Article 36 (Home Care); 10 NYCRR Part 763-766; SSL § 365-a",
        "special_requirements": "UAS-NY is the state standardized assessment. CDPAP for self-directed care. MLTC for dual-eligible members.",
    },
    "NC": {
        "name": "North Carolina",
        "medicaid_program": "NC Medicaid (Managed Care — NC Medicaid Direct and Tailored Plans)",
        "hcbs_waivers": "CAP/DA, CAP/C, Innovations Waiver",
        "assessment_tool": "NC Comprehensive Assessment Tool; FL-2 Level of Care Determination",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, nursing needs, environmental, social supports.",
        "reassessment_frequency": "Annual CAP; annual FL-2",
        "recording_consent": "one-party",
        "licensing": "Home care agencies licensed by DHSR. In-Home Aide Services licensure for personal care.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "GS 131E-135.2 et seq.; 10A NCAC 13J; NC Medicaid Clinical Coverage Policy",
        "special_requirements": "Transition to managed care ongoing. CAP/DA requires nursing facility LOC. FL-2 form required.",
    },
    "ND": {
        "name": "North Dakota",
        "medicaid_program": "North Dakota Medicaid",
        "hcbs_waivers": "HCBS Aged & Disabled, HCBS-DD, HCBS Ex-Institutional",
        "assessment_tool": "ND Uniform Assessment Instrument by Human Service Zone",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, social, financial, safety.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by NDDoH. Personal care providers through Medicaid enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "NDCC Chapter 23-17.3 (Home Health); NDAC 75-02-04 (Medicaid)",
        "special_requirements": "Human Service Zones perform independent assessments. SPED program.",
    },
    "OH": {
        "name": "Ohio",
        "medicaid_program": "Ohio Medicaid (Managed Care)",
        "hcbs_waivers": "PASSPORT, Assisted Living, SELF, OHTD",
        "assessment_tool": "Ohio Uniform Assessment Tool (UAT); PAT for LOC",
        "assessment_requirements": "PASSPORT Pre-Admission Screening. ADLs, IADLs, cognitive, behavioral, medical needs, social, environmental, informal supports, risk.",
        "reassessment_frequency": "Annual; 6-month review",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by ODH. Non-medical home care agencies licensed under ORC 3740.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "ORC 3740 (Home Care); OAC 3701-56 (Home Health); OAC 173-39 (PASSPORT)",
        "special_requirements": "PASSPORT is the main HCBS waiver for elderly. ORC 3740 licensing for non-medical home care.",
    },
    "OK": {
        "name": "Oklahoma",
        "medicaid_program": "SoonerCare",
        "hcbs_waivers": "ADvantage Waiver, In-Home Support Waiver, Homeward Bound Waiver",
        "assessment_tool": "SoonerCare Assessment Tool",
        "assessment_requirements": "Comprehensive Assessment by ADvantage case manager. ADLs, IADLs, cognitive, behavioral, medical needs, living situation, support systems, financial.",
        "reassessment_frequency": "Annual; quarterly monitoring",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by OHCA. Personal care agencies enrolled as SoonerCare providers.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "63 O.S. § 1-860.1 et seq.; OAC 317:30-5-940 (ADvantage)",
        "special_requirements": "ADvantage waiver is primary HCBS program. Consumer-directed PCS option. EVV required.",
    },
    "OR": {
        "name": "Oregon",
        "medicaid_program": "Oregon Health Plan (OHP)",
        "hcbs_waivers": "K Plan (Community First Choice 1915(k))",
        "assessment_tool": "Oregon Needs Assessment (ONA) — 19 ADL categories (most granular in US)",
        "assessment_requirements": "ADLs (19 categories), IADLs, cognitive, behavioral, medical, environmental, social supports, safety.",
        "reassessment_frequency": "Annual; review at significant change",
        "recording_consent": "two-party for in-person (Or. Rev. Stat. § 165.540); one-party for telephone",
        "licensing": "In-Home Care Agencies licensed by DHS. Home health agencies licensed by OHA.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "ORS 443.305-.350 (In-Home Care); OAR 411-034 (HCBS)",
        "special_requirements": "ONA uses 19 ADL categories. Two-party consent for in-person recording; one-party for phone. K Plan is primary service pathway.",
    },
    "PA": {
        "name": "Pennsylvania",
        "medicaid_program": "HealthChoices (Managed Care)",
        "hcbs_waivers": "OBRA Waiver (Aging), COMMCARE (TBI), Act 150, LIFE (dual-eligible)",
        "assessment_tool": "Functional Eligibility Determination (FED) Tool; interRAI Home Care; Case Management Instrument (CMI)",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, social supports, risk assessment.",
        "reassessment_frequency": "Annual",
        "recording_consent": "two-party (18 Pa.C.S. § 5704)",
        "licensing": "Home health agencies licensed by DOH. Home care agencies (non-medical) licensed under Act 69.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "28 Pa. Code Chapter 601 (Home Health); Act 69 (Home Care); 55 Pa. Code Chapter 52 (HCBS)",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. Act 69 licensing for non-medical home care. interRAI HC used for assessment. LIFE dual-eligible program.",
    },
    "RI": {
        "name": "Rhode Island",
        "medicaid_program": "Rhode Island Medicaid (RIte Care)",
        "hcbs_waivers": "HCBS Elderly/Disabled Waiver, CEDARR (IDD)",
        "assessment_tool": "RI Assessment Tool; LTSS eligibility screening by DHS",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, social supports, financial.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DOH. Personal care agencies through EOHHS enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "RIGL § 23-17-1 et seq.; RIGL § 40-8.8 (HCBS)",
        "special_requirements": "Personal choice option for consumer-directed services.",
    },
    "SC": {
        "name": "South Carolina",
        "medicaid_program": "Healthy Connections",
        "hcbs_waivers": "Community Choices Waiver, HIV/AIDS Waiver",
        "assessment_tool": "SC Assessment Tool; Level of Care determination by DHHS",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, nursing needs, environmental, support systems.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DHEC. In-Home Care providers enrolled with SCDHHS.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "SC Code § 44-69 (Home Health); SC Medicaid Provider Manual",
        "special_requirements": "Community Choices waiver is main HCBS. EVV required for PCS.",
    },
    "SD": {
        "name": "South Dakota",
        "medicaid_program": "South Dakota Medicaid",
        "hcbs_waivers": "HCBS Choices (Elderly/Disabled), HCBS-DD",
        "assessment_tool": "South Dakota Assessment Tool by DSS Assessor",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, support systems, financial.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DOH. Personal care agencies through DSS enrollment.",
        "billing_codes": "T1019 (PCS), S5125",
        "key_regulations": "SDCL 34-22 (Home Health); ARSD 67:14 (Medicaid)",
        "special_requirements": "CHOICES waiver. Rural state — telehealth provisions important.",
    },
    "TN": {
        "name": "Tennessee",
        "medicaid_program": "TennCare (Managed Care)",
        "hcbs_waivers": "CHOICES, ECF CHOICES (IDD)",
        "assessment_tool": "TN Assessment Tool; PAE (Pre-Admission Evaluation)",
        "assessment_requirements": "PAE for LOC determination; MCO comprehensive assessment. ADLs, IADLs, cognitive, behavioral, medical needs, environmental, support systems, risk.",
        "reassessment_frequency": "Annual PAE; MCO review schedule",
        "recording_consent": "one-party",
        "licensing": "Home care organizations licensed by TDH. Home health agencies also licensed.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "TCA § 68-11-201 et seq.; TN Board Rules 1200-08-25; CHOICES Program Standards",
        "special_requirements": "All LTSS through TennCare MCOs (CHOICES groups). PAE required for LTSS eligibility.",
    },
    "TX": {
        "name": "Texas",
        "medicaid_program": "STAR+PLUS (Managed Care for LTSS)",
        "hcbs_waivers": "STAR+PLUS HCBS, CLASS, DBMD, MDCP, HCS",
        "assessment_tool": "Assessment of Individual Needs (AINS) for STAR+PLUS",
        "assessment_requirements": "Comprehensive assessment by MCO service coordinator. ADLs, IADLs, cognitive, behavioral, medical, environmental, social supports, financial, risk.",
        "reassessment_frequency": "Annual; 90-day review for new members",
        "recording_consent": "one-party",
        "licensing": "HCSSAs licensed by HHSC. Home health agencies licensed separately.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135, S5120 (chore)",
        "key_regulations": "TAC Title 26 Part 1 Chapter 558 (HCSSA); HSC Chapter 142; HHSC Provider Manual",
        "special_requirements": "STAR+PLUS is largest MLTSS program in US. HCSSAs must be licensed. EVV required. Community First Choice (CFC) available.",
    },
    "UT": {
        "name": "Utah",
        "medicaid_program": "Utah Medicaid",
        "hcbs_waivers": "Aging Waiver, Physical Disabilities Waiver, New Choices Waiver, ABI Waiver",
        "assessment_tool": "Utah Assessment Tool",
        "assessment_requirements": "Level of Care assessment by case manager. ADLs, IADLs, cognitive, behavioral, medical, living environment, support systems.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by UDOH. Personal care agencies through Medicaid enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "Utah Admin Code R432-700 (Home Health); UAC R414-310 (HCBS)",
        "special_requirements": "Self-directed personal care option. New Choices waiver for nursing home transition.",
    },
    "VT": {
        "name": "Vermont",
        "medicaid_program": "Green Mountain Care",
        "hcbs_waivers": "Choices for Care (CFC) — global budget model",
        "assessment_tool": "LCARSS (Long-Term Care Assessment and Review Support System)",
        "assessment_requirements": "Comprehensive Assessment by area agency case manager. ADLs, IADLs, cognitive, behavioral, medical, environmental, informal supports, risk.",
        "reassessment_frequency": "Annual; review at significant change",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by AHS. Vermont uses a unique global budget approach.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "33 V.S.A. § 7101 et seq.; Vermont AHS Rules",
        "special_requirements": "Choices for Care operates under global budget (not traditional waiver). Flexible service model.",
    },
    "VA": {
        "name": "Virginia",
        "medicaid_program": "CCC Plus (Managed Care for LTSS)",
        "hcbs_waivers": "CCC Plus HCBS, DD Waivers, EDCD Waiver",
        "assessment_tool": "Virginia Uniform Assessment Instrument (UAI)",
        "assessment_requirements": "ADLs scored 0-4, IADLs, cognitive, behavioral, medical, environmental, social supports, risk.",
        "reassessment_frequency": "Annual UAI; MCO review schedule",
        "recording_consent": "one-party",
        "licensing": "Home health organizations licensed by VDH. Personal care agencies through DMAS enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "12VAC5-381 (Home Health); 12VAC30-120 (HCBS); Code of Virginia § 32.1-162.7 et seq.",
        "special_requirements": "CCC Plus managed LTSS for most populations. UAI is standardized assessment. Consumer-directed services option.",
    },
    "WA": {
        "name": "Washington",
        "medicaid_program": "Washington Apple Health",
        "hcbs_waivers": "COPES, New Freedom, RRTP, IHC",
        "assessment_tool": "CARE (Comprehensive Assessment Reporting Evaluation) by DSHS case manager",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, informal supports, safety, risk.",
        "reassessment_frequency": "Annual CARE; review at significant change",
        "recording_consent": "two-party (Wash. Rev. Code § 9.73.030)",
        "licensing": "Home care agencies licensed by DOH. In-Home Services agencies licensed separately.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "RCW 70.127; WAC 246-335; WAC 388-106 (HCBS)",
        "special_requirements": "TWO-PARTY CONSENT FOR RECORDING. CARE assessment generates authorized service hours. Individual Provider (IP) option for consumer-directed care.",
    },
    "WV": {
        "name": "West Virginia",
        "medicaid_program": "West Virginia Medicaid",
        "hcbs_waivers": "Aged & Disabled Waiver, IDD Waiver, TBI Waiver",
        "assessment_tool": "WV Assessment Tool; Level of Care determination by BMS",
        "assessment_requirements": "Pre-Admission Screening. ADLs, IADLs, cognitive, behavioral, medical, environmental, support systems, financial.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by OHFLAC. Personal care providers through BMS enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "WV Code § 16-5E; OHFLAC licensing rules; WV Medicaid Chapter 513 (PCS)",
        "special_requirements": "Personal Care program and ADW. Rural access challenges.",
    },
    "WI": {
        "name": "Wisconsin",
        "medicaid_program": "BadgerCare Plus",
        "hcbs_waivers": "Family Care (managed LTSS), IRIS (self-directed), Partnership",
        "assessment_tool": "Wisconsin Functional Screen Tool by ADRC",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, social supports, risk, vocational.",
        "reassessment_frequency": "Annual functional screen; semi-annual review by CMO",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DHS. Personal care agencies through Medicaid enrollment.",
        "billing_codes": "T1019 (PCS), S5125, S5130, S5135",
        "key_regulations": "Wis. Stat. § 50.49 (Home Health); DHS 133; Wis. Stat. § 46.286 (Family Care)",
        "special_requirements": "Family Care is comprehensive managed LTSS model. IRIS for self-directed care. ADRCs are gateway to services.",
    },
    "WY": {
        "name": "Wyoming",
        "medicaid_program": "EqualityCare",
        "hcbs_waivers": "Community Choices Waiver, Comprehensive DD Waiver, Supports Waiver",
        "assessment_tool": "Wyoming Assessment Tool by DFS case manager",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, support systems, safety.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by WDH. Personal care agencies through Medicaid enrollment.",
        "billing_codes": "T1019 (PCS), S5125",
        "key_regulations": "W.S. § 35-2-901 et seq.; WDH Chapter 7",
        "special_requirements": "Low population density — telehealth and remote service delivery important. Community Choices waiver is primary HCBS.",
    },
    "DC": {
        "name": "District of Columbia",
        "medicaid_program": "DC Medicaid",
        "hcbs_waivers": "EPD Waiver (Elderly and Persons with Disabilities)",
        "assessment_tool": "DC Comprehensive Assessment Tool",
        "assessment_requirements": "ADLs, IADLs, cognitive, behavioral, medical, environmental, social supports.",
        "reassessment_frequency": "Annual",
        "recording_consent": "one-party",
        "licensing": "Home health agencies licensed by DOH.",
        "billing_codes": "T1019 (PCS), S5125, S5130",
        "key_regulations": "DC Code § 44-501 et seq.",
        "special_requirements": "EPD waiver is primary HCBS program.",
    },
}


def get_state_rules(state_code: str) -> dict:
    """Get rules for a specific state. Returns empty dict if state not found."""
    return STATE_RULES.get(state_code.upper().strip(), {})


def get_recording_consent(state_code: str) -> str:
    """Return 'one-party' or 'two-party' for the given state."""
    code = state_code.upper().strip()
    if code in TWO_PARTY_CONSENT_STATES:
        return "two-party"
    if code == "OR":
        return "two-party for in-person; one-party for telephone"
    return "one-party"


def get_state_rules_for_prompt(state_code: str) -> str:
    """
    Format state-specific rules for injection into the LLM system prompt.
    Only returns the rules for the agency's state — keeps the prompt focused.
    """
    rules = get_state_rules(state_code)
    if not rules:
        return ""

    consent = get_recording_consent(state_code)
    consent_warning = ""
    if "two-party" in consent:
        consent_warning = f"\n⚠️ RECORDING CONSENT: {rules['name']} is a TWO-PARTY consent state ({rules.get('recording_consent', '')}). Explicit consent from ALL parties is REQUIRED before recording any assessment."

    return f"""
## STATE-SPECIFIC REQUIREMENTS: {rules['name']} ({state_code.upper()})
{consent_warning}

### Medicaid Program
{rules.get('medicaid_program', 'N/A')}

### HCBS Waivers
{rules.get('hcbs_waivers', 'N/A')}

### Required Assessment Tool
{rules.get('assessment_tool', 'N/A')}

### Assessment Requirements
{rules.get('assessment_requirements', 'N/A')}

### Reassessment Frequency
{rules.get('reassessment_frequency', 'N/A')}

### Licensing Requirements
{rules.get('licensing', 'N/A')}

### State Billing Codes
{rules.get('billing_codes', 'N/A')}

### Key Regulations
{rules.get('key_regulations', 'N/A')}

### Special Requirements
{rules.get('special_requirements', 'N/A')}
"""
